######################################################################
# Automatically generated by qmake (3.0) Wed Mar 6 15:34:02 2013
######################################################################

TEMPLATE = app
TARGET = QmlApp
QT += qml quick

# Input
SOURCES += main.cpp
RESOURCES += main.qrc
OTHER_FILES += main.qml

cache()
